/**
 * B站动态监控模块
 * 支持多种 API 策略和第三方备用方案
 */
const fs = require('fs');
const path = require('path');
const DATA_DIR = path.join(__dirname, '..', 'data');
const SUBSCRIPTIONS_FILE = path.join(DATA_DIR, 'subscriptions.json');
const LAST_DYNAMICS_FILE = path.join(DATA_DIR, 'last_dynamics.json');
const CONFIG_FILE = path.join(DATA_DIR, 'bilibili_config.json');
let biliConfig = { cookie: '', userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36' };
const RSSHUB_INSTANCES = ['https://rsshub.app', 'https://rsshub.rssforever.com'];
function ensureDataDir() { if (!fs.existsSync(DATA_DIR)) fs.mkdirSync(DATA_DIR, { recursive: true }); }
function loadBiliConfig() { ensureDataDir(); if (fs.existsSync(CONFIG_FILE)) { try { const c = JSON.parse(fs.readFileSync(CONFIG_FILE, 'utf-8')); biliConfig = { ...biliConfig, ...c }; } catch(e) { console.error('读取配置失败:', e.message); } } return biliConfig; }
function saveBiliConfig(config) { ensureDataDir(); biliConfig = { ...biliConfig, ...config }; fs.writeFileSync(CONFIG_FILE, JSON.stringify(biliConfig, null, 2)); }
function loadSubscriptions() { ensureDataDir(); if (fs.existsSync(SUBSCRIPTIONS_FILE)) { try { return JSON.parse(fs.readFileSync(SUBSCRIPTIONS_FILE, 'utf-8')); } catch(e) { return {}; } } return {}; }
function saveSubscriptions(subs) { ensureDataDir(); fs.writeFileSync(SUBSCRIPTIONS_FILE, JSON.stringify(subs, null, 2)); }
function loadLastDynamics() { ensureDataDir(); if (fs.existsSync(LAST_DYNAMICS_FILE)) { try { return JSON.parse(fs.readFileSync(LAST_DYNAMICS_FILE, 'utf-8')); } catch(e) { return {}; } } return {}; }
function saveLastDynamics(dyn) { ensureDataDir(); fs.writeFileSync(LAST_DYNAMICS_FILE, JSON.stringify(dyn, null, 2)); }
function getHeaders(referer) { const c = loadBiliConfig(); return { 'User-Agent': c.userAgent, 'Referer': referer || 'https://space.bilibili.com/', 'Accept': 'application/json' }; }
async function fetchDynamicOfficial(uid) { const url = `https://api.bilibili.com/x/polymer/web-dynamic/v1/feed/space?offset=&host_mid=${uid}`; try { const res = await fetch(url, { headers: getHeaders(`https://space.bilibili.com/${uid}/dynamic`) }); const text = await res.text(); if (!text.trim().startsWith('{')) throw new Error('非JSON'); const data = JSON.parse(text); if (data.code === -412) throw new Error('API被拦截，请配置Cookie'); if (data.code !== 0 || !data.data?.items?.length) return null; const item = data.data.items[0]; const modules = item.modules; if (!modules?.module_author || !modules?.module_dynamic) return null; const desc = modules.module_dynamic.desc; let content = desc?.text || ''; const major = modules.module_dynamic.major; if (major?.opus?.summary?.text) content = major.opus.summary.text; let images = []; if (major?.opus?.pics) images = major.opus.pics.map(p => p.url); else if (major?.draw?.items) images = major.draw.items.map(i => i.src); return { dynamicId: item.id_str, uid: Number(modules.module_author.mid), timestamp: modules.module_author.pub_ts, content: content.trim(), images, url: `https://t.bilibili.com/${item.id_str}` }; } catch(e) { throw e; } }
async function fetchDynamicRSSHub(uid) { for (const instance of RSSHUB_INSTANCES) { try { const url = `${instance}/bilibili/user/dynamic/${uid}`; const res = await fetch(url, { headers: { 'User-Agent': 'Mozilla/5.0' }, signal: AbortSignal.timeout(8000) }); if (res.status !== 200) continue; const text = await res.text(); const linkMatch = text.match(/<link>([^<]+)<\/link>/); const titleMatch = text.match(/<title>([^<]+)<\/title>/); if (!linkMatch) continue; return { dynamicId: linkMatch[1]?.split('/').pop(), uid, timestamp: Date.now()/1000, content: titleMatch?.[1] || '', images: [], url: linkMatch[1] }; } catch(e) { continue; } } throw new Error('所有RSSHub实例不可用'); }
async function fetchLatestDynamic(uid) { const uidStr = String(uid); console.log(`[${uidStr}] 检测动态...`); if (biliConfig.cookie) { try { console.log(`[${uidStr}] 尝试官方API...`); const result = await fetchDynamicOfficial(uid); if (result) { console.log(`[${uidStr}] 官方API成功`); return result; } } catch(e) { console.log(`[${uidStr}] 官方API失败: ${e.message}`); } } try { console.log(`[${uidStr}] 尝试RSSHub...`); return await fetchDynamicRSSHub(uid); } catch(e) { console.log(`[${uidStr}] RSSHub失败: ${e.message}`); } console.log(`[${uidStr}] 所有API失败，建议配置Cookie`); return null; }
function formatDynamicMessage(dynamic, upName) { const time = new Date(dynamic.timestamp * 1000).toLocaleString('zh-CN', { timeZone: 'Asia/Shanghai', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit', hour12: false }); let msg = `🔔 **${upName} 发布新动态**\n📅 ${time}\n\n`; if (dynamic.content) msg += `${dynamic.content.slice(0, 500)}${dynamic.content.length > 500 ? '...' : ''}\n\n`; if (dynamic.images.length > 0) msg += `🖼️ 包含 ${dynamic.images.length} 张图片\n\n`; msg += `🔗 [查看动态](${dynamic.url})`; return msg; }
async function checkUpDynamic(client, subscription, lastDynamics) { const { guildId, channelId, upList } = subscription; for (const up of upList) { const uidStr = String(up.uid); try { const latest = await fetchLatestDynamic(up.uid); if (!latest) { console.log(`[${up.name}] 暂无动态`); continue; } if (!lastDynamics[uidStr]) { console.log(`[${up.name}] 首次检测，记录: ${latest.dynamicId}`); lastDynamics[uidStr] = latest.dynamicId; continue; } if (latest.dynamicId !== lastDynamics[uidStr]) { console.log(`[${up.name}] 新动态: ${latest.dynamicId}`); try { await client.postMessage(channelId, formatDynamicMessage(latest, up.name)); } catch(e) { console.error(`[${up.name}] 发送失败:`, e.message); } lastDynamics[uidStr] = latest.dynamicId; } else { console.log(`[${up.name}] 无更新`); } } catch(e) { console.error(`[${up.name}] 异常:`, e.message); } } return lastDynamics; }
function startDynamicMonitor(client, intervalMinutes = 5) { console.log(`🕐 B站动态监控启动 (${intervalMinutes}分钟间隔)`); loadBiliConfig(); if (!biliConfig.cookie) console.log('⚠️ 未配置Cookie，将尝试第三方API'); const checkAll = async () => { const subs = loadSubscriptions(); const last = loadLastDynamics(); for (const [gid, sub] of Object.entries(subs)) { if (sub.upList?.length) Object.assign(last, await checkUpDynamic(client, sub, last)); } if (Object.keys(last).length > 0) saveLastDynamics(last); }; checkAll(); return setInterval(checkAll, intervalMinutes * 60 * 1000); }
function addSubscription(guildId, channelId, upList) { const subs = loadSubscriptions(); if (!subs[guildId]) subs[guildId] = { channelId, upList: [] }; const existing = new Set(subs[guildId].upList.map(u => String(u.uid))); for (const up of upList) { if (!existing.has(String(up.uid))) subs[guildId].upList.push(up); } saveSubscriptions(subs); return subs[guildId]; }
function removeSubscription(guildId, uid) { const subs = loadSubscriptions(); if (subs[guildId]) { subs[guildId].upList = subs[guildId].upList.filter(u => String(u.uid) !== String(uid)); if (subs[guildId].upList.length === 0) delete subs[guildId]; saveSubscriptions(subs); } }
function getSubscriptions(guildId) { return loadSubscriptions()[guildId]?.upList || []; }
async function searchUpByName(keyword) { try { const url = `https://api.bilibili.com/x/web-interface/search/type?search_type=bili_user&keyword=${encodeURIComponent(keyword)}`; const res = await fetch(url, { headers: { 'User-Agent': 'Mozilla/5.0' }, signal: AbortSignal.timeout(5000) }); if (!res.ok) return []; const data = await res.json(); if (data.code !== 0 || !data.data?.result?.length) return []; return data.data.result.map(u => ({ uid: u.mid, name: u.uname })).slice(0, 10); } catch(e) { return []; } }
function setBiliCookie(cookie) { saveBiliConfig({ cookie }); console.log('✅ Cookie已更新'); }
function getBiliConfig() { return loadBiliConfig(); }
module.exports = { startDynamicMonitor, addSubscription, removeSubscription, getSubscriptions, searchUpByName, loadSubscriptions, loadLastDynamics, fetchLatestDynamic, formatDynamicMessage, setBiliCookie, getBiliConfig };